services:
  - type: web
    name: it-service-desk
    env: docker
    plan: free
    region: singapore
    rootDir: Laravel
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: cookie
